[package]
name = "dead-pool"
version = "0.1.0"
edition = "2021"
description = "dead-pool provides a pool of threads for executing jobs."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
